### ISSUE TITLE
Mod Description 

### ISSUE THREAD

**Issue by So1embum** [chimericdream/hopper-extreme#1]
The hopper says 'Example Mod' instead of 'Hopper X-Treme' in the item tooltip and in PolyMC. 

Version 1.0.0
Minecraft 1.19.2
Fabric 0.14.9

Everything else is working great so far. Thanks for what you do.

**Comment by chimericdream** [comment]
Sorry for the long delay. I don't know how I missed both the notification of this issue as well as the name of the dang mod! Thanks for pointing it out! New version uploading to CurseForge this evening.
